Test users
voxtechnica/versionary-api pull request #2
Opened 2023-02-27 22:11 UTC by ErwinWoz

please take a closer look at TestReadAllNames and TestFilterNames, they can potentially be improved or redesigned

2023-03-03 22:16 UTC, dprinzing requested changes
A few small comments. Otherwise, this looks great!

2023-03-03 22:16 UTC, dprinzing commented on pkg/user/users_test.go
> +		expect.Equal(u20, allVersions[0])
Note that `ReadAllVersions` can return an empty slice, without error. We should verify that `allVersions` is not empty.

2023-03-03 22:16 UTC, dprinzing commented on pkg/user/users_test.go
> +		expect.Equal(len(onlyNames), len(knownIDs))
`onlyNames` might contain the name of the transient CRUD user, so we should use `GreaterOrEqual`.

2023-03-03 22:16 UTC, dprinzing commented on pkg/user/users_test.go
> +	if expect.NoError(err) && expect.NotEmpty(users) {
Since there's only one user in Organization 1, we could simplify this to verifying that the length of `users` is 1 and it contains `u11`.

2023-03-03 22:16 UTC, dprinzing commented on pkg/user/users_test.go
> +	if expect.NoError(err) && expect.NotEmpty(usersByRole) {
The CRUD user does not have the role "assistant", so we expect the number of users to be 4. This block could be simplified to testing that the length of `usersByRole` is 4.

2023-03-03 22:16 UTC, dprinzing commented on pkg/user/users_test.go
> +		expect.GreaterOrEqual(len(numOfUsers), 4)
This could be simplified to testing the length of `checkUsers`; we don't need `numOfUsers`.

2023-03-03 22:16 UTC, dprinzing commented on pkg/user/users_test.go
> +		expect.Subset(knownIDs, usersIDs)
I think these two arguments should be reversed. `userIDs` might contain the ID of the CRUD user.

2023-03-06 23:07 UTC, dprinzing approved these changes
Looks good! I think it's ready to merge.

2023-03-10 18:04 UTC, merged

2023-03-10 18:13 UTC, ErwinWoz commented
Merged branch test-users into main and deleted the branch.

Added test file for pkg/users directory

Thanks to @dprinzing for conducting the review process